import = ["~/.config/alacritty/dracula_plus.toml"]
[font]
size = 14

[font.normal]
family = "ComicShannsMonoNerdFontMono"
style = "Regular"

[window]
opacity = 0.8
blur = true

[scrolling]
history = 10000

[shell]
program = "/usr/bin/fish"

