# kitty +kitten themes Apprentice
include ./kitty-themes/themes/Dracula.conf
font_familly     ComicShannsMonoNerdFontMono-Regular
font_size        16
scrollback_lines 9999
scrollback_indicator_opacity 1.0

# color schemee
background_opacity 0.75
background_blur 30


enabled_layouts splits:split_axis=horizontal
# map
map ctrl+- launch --location=hsplit
map ctrl+\ launch --location=vsplit

# tab tab_bar_edge
tab_bar_edge down
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_background green
