# kitty +kitten themes Apprentice
include ./kitty-themes/themes/Dracula.conf
font_size        20
scrollback_lines 9999

# color schemee
background_opacity 0.6
background_blur 1


# 将 Alt 键重新映射为 Esc 前缀
# 这将确保它在 Vim/Neovim 中正确工作
# 注意：这里的 <C-a> 是一个例子，你需要将所有你使用的 Alt 组合都进行映射
# 这通常不需要，因为 'map_to_alt_gr' 已经覆盖了大部分情况，但如果你需要精确控制，可以这么做
map alt+left send_text all \x1b[1;3D
map alt+right send_text all \x1b[1;3C
# ...
# 更简单的办法是启用 kitty 的通用 alt 键模式

# 启用 alt 键作为 meta 键，以兼容 vi/emacs 快捷键
# 这个设置将让 kitty 像 xterm 一样处理 alt 键
# 这样就可以在 vim/nvim 中使用 <A-h> 这样的映射了


enabled_layouts splits:split_axis=horizontal
# map
map ctrl+- launch --location=hsplit
map ctrl+\ launch --location=vsplit

# tab tab_bar_edge
tab_bar_edge down
tab_bar_style powerline
tab_powerline_style slanted
tab_bar_background green
