# Hyprland config

env = LIBVA_DRIVER_NAME,nvidia
env = GBM_BACKEND,nvidia-drm
env = __GLX_VENDOR_LIBRARY_NAME,nvidia
env = WLR_NO_HARDWARE_CURSORS,1

exec = dunst
exec = udiskie -a
exec = nm-applet

input {
    kb_options = caps:escape
}

general {
    gaps_in = 10
    gaps_out = 10
    border_size = 1
    col.active_border = rgba(ffffffaa)
    col.inactive_border = rgba(ffffff22)
}

decoration {
    rounding = 0
}

layout = dwindle

$mainMod = SUPER

bind = $mainMod RETURN, exec, wezterm
bind = $mainMod SHIFT, exec, rofi -show drun
bind = $mainMod Q, exec, flameshot gui

bind = $mainMod J, movefocus, l
bind = $mainMod K, movefocus, r
bind = $mainMod H, resizeactive, -5 0
bind = $mainMod L, resizeactive, +5 0

bind = $mainMod T, layout, split
bind = $mainMod F, exec, togglefloating
bind = $mainMod M, fullscreen, 0
bind = $mainMod TAB, workspace, e+1
bind = $mainMod SHIFT C, kill
bind = $mainMod SHIFT SPACE, togglefloating
bind = $mainMod 0, workspace, all

bind = $mainMod ., focus, monitor right
bind = $mainMod ,, focus, monitor left
bind = $mainMod SHIFT ., move, monitor right
bind = $mainMod SHIFT ,, move, monitor left

bind = $mainMod MINUS, gapsinner, current -5
bind = $mainMod EQUAL, gapsinner, current +5
bind = $mainMod SHIFT MINUS, gapsinner, current set 0
bind = $mainMod SHIFT EQUAL, gapsinner, current set 10

bind = $mainMod SHIFT E, exit

bind = $mainMod 1, workspace, 1
bind = $mainMod 2, workspace, 2
bind = $mainMod 3, workspace, 3
bind = $mainMod 4, workspace, 4
bind = $mainMod 5, workspace, 5
bind = $mainMod 6, workspace, 6
bind = $mainMod 7, workspace, 7
bind = $mainMod 8, workspace, 8
bind = $mainMod 9, workspace, 9

bind = $mainMod SHIFT 1, movetoworkspace, 1
bind = $mainMod SHIFT 2, movetoworkspace, 2
bind = $mainMod SHIFT 3, movetoworkspace, 3
bind = $mainMod SHIFT 4, movetoworkspace, 4
bind = $mainMod SHIFT 5, movetoworkspace, 5
bind = $mainMod SHIFT 6, movetoworkspace, 6
bind = $mainMod SHIFT 7, movetoworkspace, 7
bind = $mainMod SHIFT 8, movetoworkspace, 8
bind = $mainMod SHIFT 9, movetoworkspace, 9

bindm = $mainMod, mouse:272, movewindow
bindm = $mainMod, mouse:273, resizewindow

windowrulevs = float, class:^(Gimp)$
windowrulevs = workspace 9, class:^(firefox)$

gestures {
    workspace_swipe = on
}

misc {
    disable_hyprland_logo = true
    disable_splash_rendering = true
}
